### ISSUE TITLE
Problem trying to run it

### ISSUE THREAD

**Issue by fernandocoronatomf** [err0r500/go-realworld-clean#3]
Hi,  Thanks for the contribution with this project.

I am trying to run it but getting this error following the instructions

![image](https://user-images.githubusercontent.com/1309374/71551074-15299700-2a32-11ea-86c5-9f7152e74563.png)

**Comment by err0r500** [comment]
Sorry for the delay @fernandocoronatomf and thanks for the issue. 
I'll have a look ASAP.

**Comment by err0r500** [comment]
I switched to go modules at 589f5e8764f0a18e7f5b867742e5dfcefd1120a0 you should not experience this problem anymore.
